# Generated by Django 3.0.2 on 2020-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=150)),
                ('game', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=150)),
            ],
        ),
    ]
