# Generated by Django 3.0.2 on 2020-02-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
